from __future__ import annotations

import json
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOC_DIR = ROOT / "doc"
OUT_FILE = ROOT / "src" / "generated" / "game-config.js"

NS = {
    "a": "http://schemas.openxmlformats.org/spreadsheetml/2006/main",
    "r": "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
}

FILES = {
    "realm_rows": "境界数值配表.xlsx",
    "pill_rows": "丹药列表.xlsx",
    "skill_rows": "功法列表.xlsx",
    "monster_rows": "怪物列表.xlsx",
    "material_rows": "材料与杂物列表.xlsx",
    "equipment_rows": "装备列表.xlsx",
    "map_rows": "游戏地图配置.xlsx",
    "command_rows": "指令配置总表.xlsx",
}


def load_sheet_rows(path: Path) -> list[dict[str, str]]:
    with zipfile.ZipFile(path) as zf:
        shared_strings = []
        if "xl/sharedStrings.xml" in zf.namelist():
            sroot = ET.fromstring(zf.read("xl/sharedStrings.xml"))
            for si in sroot.findall("a:si", NS):
                shared_strings.append("".join(t.text or "" for t in si.findall(".//a:t", NS)))

        workbook = ET.fromstring(zf.read("xl/workbook.xml"))
        rels = ET.fromstring(zf.read("xl/_rels/workbook.xml.rels"))
        rel_map = {rel.attrib["Id"]: rel.attrib["Target"] for rel in rels}
        first_sheet = workbook.find("a:sheets/a:sheet", NS)
        if first_sheet is None:
            return []
        rid = first_sheet.attrib["{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id"]
        target = "xl/" + rel_map[rid]
        root = ET.fromstring(zf.read(target))
        rows = root.findall(".//a:sheetData/a:row", NS)
        if not rows:
            return []

        data_rows: list[list[str]] = []
        for row in rows:
            values: list[str] = []
            for cell in row.findall("a:c", NS):
                cell_type = cell.attrib.get("t")
                value_node = cell.find("a:v", NS)
                if value_node is None:
                    values.append("")
                elif cell_type == "s":
                    values.append(shared_strings[int(value_node.text)])
                else:
                    values.append(value_node.text or "")
            data_rows.append(values)

        headers = [str(item).strip() for item in data_rows[0]]
        result: list[dict[str, str]] = []
        for row in data_rows[1:]:
            if not any(str(item).strip() for item in row):
                continue
            padded = row + [""] * (len(headers) - len(row))
            result.append({headers[i]: str(padded[i]).strip() for i in range(len(headers))})
        return result


def main() -> None:
    payload = {}
    for export_name, filename in FILES.items():
        payload[export_name] = load_sheet_rows(DOC_DIR / filename)

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Auto-generated by scripts/extract_game_configs.py",
        "// Source of truth: doc/*.xlsx",
    ]
    for export_name, rows in payload.items():
        lines.append(f"export const {export_name} = {json.dumps(rows, ensure_ascii=False, indent=2)};")
    OUT_FILE.write_text("\n\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated: {OUT_FILE}")


if __name__ == "__main__":
    main()
